eureka:
  instance:
    hostname: localhost

  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8091

spring:
  application:
    name: ressource
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ressource
    username: root
    password: taha1234
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect



