eureka:
  client:
    register-with-eureka: false

server:
  port: 8222

spring:
  application:
    name: gateway
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: ressourceService
          predicates:
            - Path=/api/ressourceService/**
          uri: http://localhost:8091

        - id: panneService
          predicates:
            - Path=/api/panneService/**
          uri: http://localhost:8092


